export const staticProducts = [
  {
    id: 1,
    productName: "Fresh Tomatoes",
    description: "Freshly picked organic tomatoes from local farms.",
    price: "2.5",
    category: "Vegetables",
    farmerId: 101,
    farmerName: "John's Farm",
  },
  {
    id: 2,
    productName: "Organic Apples",
    description: "Crisp and juicy organic apples.",
    price: "3.0",
    category: "Fruits",
    farmerId: 102,
    farmerName: "Green Valley Orchards",
  },
  {
    id: 3,
    productName: "Farm Fresh Eggs",
    description: "Free-range eggs from healthy hens.",
    price: "4.0",
    category: "Dairy",
    farmerId: 103,
    farmerName: "Sunny Side Farm",
  },
  {
    id: 4,
    productName: "Grass-fed Beef",
    description: "Premium quality grass-fed beef.",
    price: "10.0",
    category: "Meat",
    farmerId: 104,
    farmerName: "Highland Ranch",
  },
];
